{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "golden-path-api.labels" . | nindent 4 }}
    # Pod Security Standards (PSS) - https://kubernetes.io/docs/concepts/security/pod-security-standards/
    pod-security.kubernetes.io/enforce: {{ .Values.namespace.podSecurityStandard.enforce | default "restricted" }}
    pod-security.kubernetes.io/enforce-version: {{ .Values.namespace.podSecurityStandard.version | default "latest" }}
    pod-security.kubernetes.io/warn: {{ .Values.namespace.podSecurityStandard.warn | default "restricted" }}
    pod-security.kubernetes.io/warn-version: {{ .Values.namespace.podSecurityStandard.version | default "latest" }}
    pod-security.kubernetes.io/audit: {{ .Values.namespace.podSecurityStandard.audit | default "restricted" }}
    pod-security.kubernetes.io/audit-version: {{ .Values.namespace.podSecurityStandard.version | default "latest" }}
{{- end }}
