{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "golden-path-api.fullname" . }}
  labels:
    {{- include "golden-path-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "golden-path-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
{{- end }}
